apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: dvlp-app
spec:
  selector:
    matchLabels:
      app: dvlp-app
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: dvlp-app
    spec:
      containers:
      - name: dvlp-2018
        image: kimschles/dvlp-2018:latest
        command: ["npm", "start"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80