# Note: this service doesn't work. Use this command: 
# kubectl expose deployment dvlp-app -n dvlp-k8s --type="LoadBalancer"

apiVersion: v1
kind: Service
metadata:
  name: dvlp-app
  labels:
    app: dvlp-app
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: dvlp-app


